void handleMaisCnf(){
  String user = autenticar(); if(user.length()<=0) return server.requestAuthentication();
  String pg;
  pg=F(
  "<html>\n"
  "<head>\n"
  "<meta name='viewport' content='width=device-width, initial-scale=1'>\n"
  "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>\n"
  "<title>");pg+=DeviceID;pg+=F("</title>\n"
  "<style>\n"
  "  body{margin:0}\n"
  "  body,html, input, button,label,p,span {font: 18px Verdana, Arial, Helvetica, sans-serif;}\n"
  "  .btn0{border-radius:6px;width:42px;height:32px}\n"
  "  .btn1{border-radius:6px;width:106px;height:40px}\n"
  "  .divbl{border-style:solid;border-radius:8px;margin-bottom:8px;padding:6px;border-color:#e1e1e1}\n"
  "  p{margin:8px;padding:0;line-height:200%}\n"
  "</style>\n"
  "</head>\n"
  "<body onLoad='iniciar()'>\n"
"<script>\n"
"\n"
"function iniciar(){\n"
"  fields='DeviceID,BackgroundColor,Color1,Temperatura,Umidade,Lumi,Reles,Sensores2';\n"
"  if(localStorage.getItem('fields')){fields=localStorage.getItem('fields');}\n"
"  fields=','+fields+',';\n"
"  if(fields.indexOf(',Temperatura,')>=0) Temperatura.checked=true;\n"
"  if(fields.indexOf(',Umidade,')>=0) Umidade.checked=true;\n"
"  if(fields.indexOf(',Lumi,')>=0) Lumi.checked=true;\n"
"  if(fields.indexOf(',Reles,')>=0) Reles.checked=true;\n"
"  if(fields.indexOf(',Sensores2,')>=0) Sensores2.checked=true;\n"
"  if(fields.indexOf(',Versao,')>=0) Versao.checked=true;\n"
"  loadLista();\n"
"  iniciarBusca();\n"
"}\n"
"\n"
"function salvar(){\n"
"  sa='DeviceID,BackgroundColor,Color1';\n"
"  if(Temperatura.checked) sa+=',Temperatura';\n"
"  if(Umidade.checked) sa+=',Umidade';\n"
"  if(Lumi.checked) sa+=',Lumi';\n"
"  if(Reles.checked) sa+=',Reles';\n"
"  if(Sensores2.checked) sa+=',Sensores2';\n"
"  if(Versao.checked) sa+=',Versao';\n"
"  localStorage.setItem('fields', sa);\n"
"}\n"
"\n"
"</script>\n"
"<script>\n"
"\n"
"function loadLista(){\n"
"  lista=new Array();lista2=new Array();\n"
"  if(localStorage.getItem('lista')){\n"
"    sa = localStorage.getItem('lista');\n"
"    span01.innerHTML='';\n"
"    while(sa.indexOf(';')>=0){\n"
"      sb=sa.substring(0,sa.indexOf(';'));\n"
"      sa=sa.substring(sa.indexOf(';')+1);\n"
"      lista[lista.length]=sb;\n"
"      DeviceID=sb.substring(0,sb.indexOf(','));\n"
"      sb=sb.substring(sb.indexOf(',')+1);\n"
"      Link=sb.substring(0,sb.indexOf(','));\n"
"      sb=sb.substring(sb.indexOf(',')+1);\n"
"      bgc=sb.substring(0,sb.indexOf(','));\n"
"      boc=sb.substring(sb.indexOf(',')+1);\n"
"      lista2[lista2.length]=Link;\n"
"      span01.innerHTML+=DeviceID+'<br>';\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"function reiniciarBusca(){\n"
"  if(confirm('Limpar dados salvos neste computador?')){\n"
"    localStorage.removeItem('lista');\n"
"    localStorage.removeItem('listaPosX');\n"
"    localStorage.removeItem('listaPosY');\n"
//"    localStorage.removeItem('fields');\n"
"    location.reload();\n"
"  }\n"
"}\n"
"\n"
"ini=8002;fim=8050;\n"
"timeout=500;\n"
"lista=new Array();lista2=new Array();\n"
"url=location.href;\n"
"url=url.substring(url.indexOf('//')+2);\n"
"url=url+'/'; url=url.substring(0,url.indexOf('/'));\n"
"if(url.indexOf(':')>-1){\n"
"  sa=url.substring(url.indexOf(':')+1);\n"
"  url=url.substring(0,url.indexOf(':')+1);\n"
"}else{\n"
" sa=url;url='';\n"
" while(sa.indexOf('.')>-1){\n"
"   url=url+sa.substring(0,sa.indexOf('.')+1);\n"
"   sa=sa.substring(sa.indexOf('.')+1);\n"
" }\n"
" ini=ini-8000;fim=fim-8000;\n"
"}\n"
"url='http://'+url;\n"
"sa=sa.replace('/','');sa++;sa--;\n"
"\n"
"var client = new XMLHttpRequest();\n"
"client.onreadystatechange = function() {\n"
" if (this.readyState==4){\n"
"   sa=url2;\n"
"   if(this.status==200){\n"
"     var myObj=JSON.parse(this.responseText);\n"
"     DeviceID='';\n"
"     bgc='#0000FF';boc='#FFFFFF';\n"
"     if(typeof myObj.DeviceID!='undefined'){ DeviceID=myObj.DeviceID; }\n"
"     if(typeof myObj.BackgroundColor!='undefined'){ bgc=myObj.BackgroundColor; }\n"
"     if(typeof myObj.Color1!='undefined'){ boc=myObj.Color1; }\n"
"     sb=DeviceID+','+url2+','+bgc+','+boc;\n"
"     if(lista2.indexOf(url2)<0 && DeviceID!=''){\n"
"       lista[lista.length]=sb;\n"
"       lista2[lista2.length]=url2;\n"
"       span01.innerHTML+=myObj.DeviceID+'<br>';\n"
"       sa='';\n"
"       for (i in lista){sa += lista[i]+';';}\n"
"       localStorage.setItem('lista', sa);\n"
"     }\n"
"   }\n"
"   ia++;\n"
"   if(ia<=fim){\n"
"     url2=url+ia;\n"
"     span02.innerHTML=timeout+' '+url2;\n"
"     client.open('GET', url2+'/json?fields=DeviceID,BackgroundColor,Color1', true);\n"
"     client.timeout=timeout; client.send();\n"
"   }else{\n"
"     ia=ini;timeout*=2;client.timeout = timeout;\n"
"     if(timeout<=4000){iniciar();}\n"
"     span02.innerHTML='';\n"
"   }\n"
" }\n"
"}\n"
"\n"
"function iniciarBusca(){\n"
"  ia=ini;\n"
"  url2=url+ia;\n"
"  span02.innerHTML=timeout+' '+url2;\n"
"  client.open('GET', url2+'/json?fields=DeviceID,BackgroundColor,Color1', true);\n"
"  client.timeout=timeout; client.send();  \n"
"}\n"
"\n"
"</script>\n"
"\n"
"<div align=center width=100%>\n"
"  <table id='tableHeader' border='0' cellspacing='6' cellpadding='0' style='background-color:");pg+=backgroundColor;pg+=F(";color:");pg+=Color1;pg+=F(";width:100%;'>\n"
"    <tr height='32' style='font-size:20px'>\n"
"      <td style='width:15%;text-align:left;'><input type='button' class='btn0' value='<' onclick='history.go(-1)'></td>\n"
"      <td style='width:70%;text-align:center;'><b>Op&ccedil;&otilde;es</b></td>\n"
"      <td style='width:15%' align='right'><input type=button class=btn0 onclick='location.href=\"maislay\"' value='#'></td>\n"
"    </tr>\n"
"  </table>\n"
"  <table border='0' cellspacing='0' cellpadding='0' style='width:100%;max-width:360px'>\n"
"    <tr>\n"
"      <td style='padding:8px;width:100%;max-width:360px'>\n"
"        <div class='divbl' align=center>\n"
"          <table><tr><td align=left>\n"
"            <p>\n"
"            <label><input type=checkbox id=Temperatura onclick=salvar()> Temperatura</label><br>\n"
"            <label><input type=checkbox id=Umidade onclick=salvar()> Umidade</label><br>\n"
"            <label><input type=checkbox id=Sensores2 onclick=salvar()> Sensores</label><br>\n"
"            <label><input type=checkbox id=Lumi onclick=salvar()> Luminosidade</label><br>\n"
"            <label><input type=checkbox id=Reles onclick=salvar()> Reles</label><br>\n"
"            <label><input type=checkbox id=Versao onclick=salvar()> Versao</label>\n"
"            </p>\n"
"          </td></tr></table>\n"
"        </div>\n"

"        <div class='divbl' align=center>\n"
"          <table border='0' cellspacing='0' cellpadding='0' width='100%'><tr>"
"<td width='10%' valign=top><button onclick='reiniciarBusca()' style='border-radius:6px;'>Reiniciar<br>Busca</button></td>"
"<td width='90%' align=left style=padding-left:8px>\n"
"            <span id=span01></span>\n"
"          </td></tr></table>\n"
"        </div>\n"

"<div class='divbl' align='center'>\n"
"Acesso Local<br><a href='http://");pg+=WiFi.localIP().toString();pg+=F("'>http://");pg+=WiFi.localIP().toString();pg+=F("</a><br>\n"
"Acesso Remoto<br><a href='");pg+=myip;pg+=F("'>");pg+=myip;pg+=F("</a>\n"
"</div>\n"

"      </td>\n"
"    </tr>\n"
"  </table>\n"
"<span id=span02 style='font-size:14px;'>Procurando módulos</span>\n"
"</div>\n"
"</body>\n"
"</html>\n"
  );
  server.send(200, "text/html", pg);
}

